### ISSUE TITLE
MVP API + initial commit: 

### ISSUE THREAD

**Issue by eba472** [eba472/mango-mobile#6]

**Comment by eba472** [comment]
Hi @Tserensodnom-Enkhbaatar,

Niice goy hurdan hiisen baina,

Heden comment baina:
 - **api/** dotor express app, **mobile/** dotor flutter app hiiy gej tolowloson bolohoor.
 Shine `express` app-aa `api/` folder-luu zooy. 
 - Bas `.gitignore` buruu ajillaj baih shig baina. package-lock.json, node-modules 2 github ruu appload hiigdchihij. Teriig zasay
 - **api/** folder dotroo README.md uusgeed node version, start script ntr ee bichwel humuust amar baih, 
 - Nileen olon file uussen baina. https://expressjs.com/en/starter/installing.html tutorial-ii dagaad hiiwel ih tsoohon file tai app uuseh baih.
 
 Sorry for long chat :)

**Comment by Tses0** [comment]
Looks like mango-api already has expressJs installed. What should I do for the initial commit in detail?

**Comment by eba472** [comment]
> Looks like mango-api already has expressJs installed. What should I do for the initial commit in detail?

Anhaan, mango-api repo-g ern ashiglahgui mango-mobile/api dotor shine api uusegey
